# Generated by Django 2.1.4 on 2018-12-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20181214_2110'),
        ('review', '0002_auto_20181217_1213'),
    ]

    operations = [
    ]
