# Generated by Django 2.1.4 on 2018-12-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='음식이름')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('has_side_dishes', models.BooleanField(default=False, verbose_name='사이드메뉴')),
                ('food_info', models.TextField(blank=True, verbose_name='음식정보')),
            ],
            options={
                'verbose_name': '음식',
                'verbose_name_plural': '음식 목록',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='음식분류')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴 목록',
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(blank=True, upload_to='food', verbose_name='음식사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Food', verbose_name='음식')),
            ],
            options={
                'verbose_name': '음식사진',
                'verbose_name_plural': '음식사진 목록',
            },
        ),
        migrations.CreateModel(
            name='SideDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='사이드메뉴이름')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수선택')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Food', verbose_name='음식')),
            ],
            options={
                'verbose_name': '사이드메뉴',
                'verbose_name_plural': '사이드메뉴 목록',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상점이름')),
                ('store_info', models.TextField(blank=True, verbose_name='상점소개')),
                ('origin_info', models.TextField(blank=True, verbose_name='원산지 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('least_cost', models.PositiveIntegerField(default=0, verbose_name='최소주문금액')),
                ('takeout', models.BooleanField(default=False, verbose_name='테이크아웃')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='배달팁')),
            ],
            options={
                'verbose_name': '상점',
                'verbose_name_plural': '상점 목록',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(blank=True, upload_to='store', verbose_name='상점사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='상점')),
            ],
            options={
                'verbose_name': '상점이미지',
                'verbose_name_plural': '상점이미지 목록',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.StoreCategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='상점주'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='상점'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.FoodCategory', verbose_name='메뉴'),
        ),
    ]
