# Generated by Django 2.1.4 on 2018-12-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='별점평균'),
        ),
    ]
