# Generated by Django 2.1.3 on 2018-11-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '상점', 'verbose_name_plural': '상점 목록'},
        ),
    ]
