# Generated by Django 2.1.3 on 2018-11-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='음식이름')),
                ('img_profile', models.ImageField(blank=True, upload_to='food', verbose_name='음식이미지')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='음식점')),
            ],
            options={
                'verbose_name': '음식',
                'verbose_name_plural': '음식 목록',
            },
        ),
    ]
