# Generated by Django 2.1.4 on 2018-12-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='사이드메뉴이름')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수선택')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Food', verbose_name='음식')),
            ],
            options={
                'verbose_name': '사이드메뉴',
                'verbose_name_plural': '사이드메뉴 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='storeimage',
            options={'verbose_name': '상점이미지', 'verbose_name_plural': '상점이미지 목록'},
        ),
        migrations.AddField(
            model_name='foodimage',
            name='has_side_dishes',
            field=models.BooleanField(default=False, verbose_name='사이드메뉴'),
        ),
    ]
