# Generated by Django 2.1.4 on 2018-12-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181208_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='set_menu',
        ),
        migrations.RemoveField(
            model_name='foodimage',
            name='has_side_dishes',
        ),
        migrations.AddField(
            model_name='food',
            name='has_side_dishes',
            field=models.BooleanField(default=False, verbose_name='사이드메뉴'),
        ),
    ]
