# Generated by Django 2.1.3 on 2018-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_food_food_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='set_menu',
            field=models.BooleanField(default=False, verbose_name='세트'),
        ),
    ]
