# Generated by Django 2.1.4 on 2018-12-17 03:13


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_address', models.CharField(max_length=100, verbose_name='지번주소')),
                ('address', models.CharField(max_length=100, verbose_name='도로명 주소')),
                ('detail_address', models.CharField(blank=True, max_length=100, verbose_name='상세주소')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='is_store_address_set', related_query_name='is_store_address',
                                            to='store.Store', verbose_name='상점')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='is_host_address_set', related_query_name='is_host_address',
                                           to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소 목록',
            },
        ),
    ]
