# Generated by Django 2.1.4 on 2018-12-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_address', models.CharField(max_length=100, verbose_name='지번주소')),
                ('address', models.CharField(max_length=100, verbose_name='도로명 주소')),
                ('detail_address', models.CharField(max_length=100, verbose_name='상세주소')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_store_address_set', related_query_name='is_store_address', to='store.Store', verbose_name='상점')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소 목록',
            },
        ),
    ]
