# Generated by Django 2.1.4 on 2018-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_address', models.CharField(max_length=100, verbose_name='지번주소')),
                ('address', models.CharField(max_length=100, verbose_name='도로명 주소')),
                ('detail_address', models.CharField(blank=True, max_length=100, verbose_name='상세주소')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소 목록',
            },
        ),
    ]
