# Generated by Django 2.1.4 on 2018-12-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='경도'),
        ),
    ]
