# Generated by Django 2.1.4 on 2018-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20181210_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='상세주소'),
        ),
    ]
